### ISSUE TITLE
Mistake in document

### ISSUE THREAD

**Issue by minhkhoi1026** [kaylode/ivos#50]
In `README.md`, there is a line mentioned about `requirements.txt`:
> Go to root folder, run pip install -r requirements.txt

However, there is no such file in root folder, instead the folder contains `environment.yml`. I think there is a mistake in document and you should fix it ^^.

**Comment by kaylode** [comment]
Oops we didn't notice there was an open issue. Thanks a ton @minhkhoi1026 , that was a huge mistake.
